### save link
POST http://localhost:8080/
Cookie: test

http://test.com

### /api/user/urls
http://localhost:8080/api/user/urls


### /api/internal/stats
http://localhost:8080/api/internal/stats
X-Real-IP: 192.168.0.159

### save GRPC link
GRPC localhost:8080/shortener.Shortener/

http://test.com