version: "3.6"
services:
    postgres:
        container_name: postgres_shorten
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: shorten
            PGDATA: /tmp
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
            - "5432:5432"